"""Core trading tables: markets, market_prices, orders, trades, positions,
strategies, backtests, backtest_trades, intents.

Revision ID: 004
Revises: 003
Create Date: 2026-09-04 00:03:00.000000+00:00

PLAN.md §3 records that only migration `001` ever ran
(`price_history`/`trade_history`/`tracked_traders`/`backtest_runs`); the
nine tables this migration creates were declared as SQLAlchemy models
(`app/models/{market,trade,position,strategy,backtest}.py`) but NEVER
received a migration of their own — any database that has ever held them
got them via `Base.metadata.create_all()` on a dev box, never via
Alembic. This migration is hand-written from the CURRENT model
definitions (T15, PLAN.md D7/D13) rather than autogenerated, and its
`upgrade()` must match `Base.metadata` exactly or this chain and a fresh
`create_all()` diverge forever — it was checked against
`str(CreateTable(table).compile(dialect=postgresql.dialect()))` for every
table below before being written down.

`tracked_traders` is deliberately NOT referenced here (it was dropped for
good in `002`, PLAN.md D2); this migration only ever touches the nine
tables named above.

T15 (PLAN.md D7) additions on top of the original models, all reflected
below:
  - `Order`/`Trade`/`Position` gain `venue`/`mode` (paper-vs-live
    separator, GUARDRAILS.md §1.2, indexed and `CHECK`-constrained —
    mirrors `app.venues.types.VenueId` / `app.venues.registry.TradingMode`
    without importing them; see `app.models.trade`'s module docstring).
  - `Order` gains `client_order_id` (the venue idempotency key,
    `UNIQUE`), `intent_id`, `outcome`; `order_id` becomes nullable
    (assigned only once the venue acks the order).
  - `Trade` gains `venue`, `outcome`, `liquidity`, `mode`; `tx_hash`
    becomes nullable (Kalshi trades have no on-chain settlement).
  - `Position` gains `venue`, `mode`, `intent_id`, `hold_to_resolution`,
    `settled_at`, `settlement_outcome`.
  - `Market` gains `venue` (default `'polymarket'`); `condition_id`'s
    formerly-unique index becomes a plain (non-unique) index plus an
    explicit composite `UNIQUE (venue, condition_id)` — the real
    identity of a market is now the (venue, condition_id) pair, not
    `condition_id` alone.
  - New `intents` table (`app.models.intent.IntentRecord`): one row per
    `Intent` submission, written by `OrderRouter` (T14) BEFORE any leg is
    placed, so a crash mid-submission still leaves an audit trail.

Enum reuse: `orderside` (`BUY`/`SELL`) is shared by `orders.side`,
`trades.side`, AND `backtest_trades.side` — created ONCE via a raw
`CREATE TYPE` (offline-safe: a literal string, no connection needed) and
referenced everywhere else with `create_type=False` so `op.create_table`
never tries to (re)create it. `orderstatus`, `ordertype`, `strategytype`,
`backteststatus` are each used by exactly one table and are declared
inline, same as `001` did for `tradeside`/`tradeoutcome`/
`backtestrunstatus`.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "004"
down_revision: Union[str, None] = "003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: Mirrors `app.models.base.JSONDict`/`JSONList`: plain JSON on SQLite
#: (tests), JSONB on Postgres. Declared here rather than imported so this
#: migration stays valid if the model module is later refactored — a
#: migration describes the schema as it was, not as the models are now
#: (same rationale `003` used).
_JSON_TYPE = sa.JSON(none_as_null=True).with_variant(
    postgresql.JSONB(none_as_null=True), "postgresql"
)

#: Shared `orders.side` / `trades.side` / `backtest_trades.side` enum
#: type. `create_type=False` on every use after the first explicit
#: `CREATE TYPE` below (see module docstring) — passing the SAME name
#: with `create_type=False` tells SQLAlchemy's DDL compiler not to emit
#: its own `CREATE TYPE orderside …` for that column, so three
#: `op.create_table` calls sharing this type don't collide.
_ORDER_SIDE_ENUM = postgresql.ENUM(
    "BUY", "SELL", name="orderside", create_type=False
)


def upgrade() -> None:
    # `orderside` is used by three tables below; create the Postgres
    # enum type exactly once, up front, as a literal (offline-safe)
    # statement rather than via `Enum.create(bind, checkfirst=True)`,
    # which would require a real connection and break `--sql` generation.
    op.execute("CREATE TYPE orderside AS ENUM ('BUY', 'SELL')")

    # --- markets ---------------------------------------------------
    op.create_table(
        "markets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("venue", sa.String(16), nullable=False),
        sa.Column("condition_id", sa.String(66), nullable=False),
        sa.Column("question_id", sa.String(66), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(100), nullable=True),
        sa.Column("token_ids", _JSON_TYPE, nullable=False),
        sa.Column("outcomes", _JSON_TYPE, nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.Column("resolution_outcome", sa.String(50), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("volume_24h", sa.Float(), nullable=False),
        sa.Column("total_volume", sa.Float(), nullable=False),
        sa.Column("liquidity", sa.Float(), nullable=False),
        sa.Column("outcome_prices", _JSON_TYPE, nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("icon_url", sa.Text(), nullable=True),
        sa.Column("extra_data", _JSON_TYPE, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "venue", "condition_id", name="uq_markets_venue_condition_id"
        ),
        sa.CheckConstraint(
            "venue IN ('polymarket', 'kalshi')", name="ck_markets_venue_valid"
        ),
    )
    op.create_index("ix_markets_category", "markets", ["category"])
    op.create_index("ix_markets_is_active", "markets", ["is_active"])
    op.create_index("ix_markets_venue", "markets", ["venue"])
    op.create_index("ix_markets_end_date", "markets", ["end_date"])
    op.create_index("ix_markets_condition_id", "markets", ["condition_id"])

    # --- market_prices -----------------------------------------------
    op.create_table(
        "market_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(50), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"]),
    )
    op.create_index("ix_market_prices_market_id", "market_prices", ["market_id"])
    op.create_index("ix_market_prices_timestamp", "market_prices", ["timestamp"])
    op.create_index(
        "ix_market_prices_market_timestamp",
        "market_prices",
        ["market_id", "timestamp"],
    )

    # --- strategies ----------------------------------------------------
    op.create_table(
        "strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "strategy_type",
            sa.Enum(
                "ARBITRAGE",
                "MOMENTUM",
                "MEAN_REVERSION",
                "MARKET_MAKING",
                "CUSTOM",
                name="strategytype",
            ),
            nullable=False,
        ),
        sa.Column("parameters", _JSON_TYPE, nullable=False),
        sa.Column("default_parameters", _JSON_TYPE, nullable=False),
        sa.Column("max_position_size", sa.Float(), nullable=False),
        sa.Column("max_daily_loss", sa.Float(), nullable=False),
        sa.Column("stop_loss_pct", sa.Float(), nullable=True),
        sa.Column("take_profit_pct", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_backtested", sa.Boolean(), nullable=False),
        sa.Column("total_trades", sa.Integer(), nullable=False),
        sa.Column("win_rate", sa.Float(), nullable=False),
        sa.Column("avg_profit", sa.Float(), nullable=False),
        sa.Column("sharpe_ratio", sa.Float(), nullable=True),
        sa.Column("max_drawdown", sa.Float(), nullable=True),
        sa.Column("module_path", sa.String(255), nullable=True),
        sa.Column("class_name", sa.String(100), nullable=True),
        sa.Column("extra_data", _JSON_TYPE, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    # --- orders ----------------------------------------------------
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(100), nullable=True),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("venue", sa.String(16), nullable=False),
        sa.Column("client_order_id", sa.String(64), nullable=False),
        sa.Column("intent_id", sa.String(64), nullable=True),
        sa.Column("token_id", sa.String(100), nullable=False),
        sa.Column("outcome", sa.String(50), nullable=False),
        sa.Column("side", _ORDER_SIDE_ENUM, nullable=False),
        sa.Column(
            "order_type",
            sa.Enum("GTC", "GTD", "FOK", name="ordertype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "OPEN",
                "FILLED",
                "PARTIALLY_FILLED",
                "CANCELLED",
                "EXPIRED",
                "FAILED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("mode", sa.String(8), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("size", sa.Float(), nullable=False),
        sa.Column("filled_size", sa.Float(), nullable=False),
        sa.Column("remaining_size", sa.Float(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tx_hash", sa.String(66), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("extra_data", _JSON_TYPE, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"]),
        sa.UniqueConstraint("client_order_id"),
        sa.CheckConstraint(
            "venue IN ('polymarket', 'kalshi')", name="ck_orders_venue_valid"
        ),
        sa.CheckConstraint("mode IN ('paper', 'live')", name="ck_orders_mode_valid"),
    )
    op.create_index("ix_orders_market_id", "orders", ["market_id"])
    op.create_index("ix_orders_venue", "orders", ["venue"])
    op.create_index("ix_orders_intent_id", "orders", ["intent_id"])
    op.create_index("ix_orders_mode", "orders", ["mode"])
    op.create_index("ix_orders_status", "orders", ["status"])
    op.create_index("ix_orders_created_at", "orders", ["created_at"])
    op.create_index("ix_orders_order_id", "orders", ["order_id"], unique=True)

    # --- trades ------------------------------------------------------
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trade_id", sa.String(100), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("venue", sa.String(16), nullable=False),
        sa.Column("token_id", sa.String(100), nullable=False),
        sa.Column("outcome", sa.String(50), nullable=False),
        sa.Column("side", _ORDER_SIDE_ENUM, nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("size", sa.Float(), nullable=False),
        sa.Column("fee", sa.Float(), nullable=False),
        sa.Column("liquidity", sa.String(8), nullable=True),
        sa.Column("mode", sa.String(8), nullable=False),
        sa.Column("maker_address", sa.String(42), nullable=True),
        sa.Column("taker_address", sa.String(42), nullable=True),
        sa.Column("tx_hash", sa.String(66), nullable=True),
        sa.Column("block_number", sa.Integer(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extra_data", _JSON_TYPE, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"]),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"]),
        sa.CheckConstraint(
            "venue IN ('polymarket', 'kalshi')", name="ck_trades_venue_valid"
        ),
        sa.CheckConstraint("mode IN ('paper', 'live')", name="ck_trades_mode_valid"),
        sa.CheckConstraint(
            "liquidity IN ('maker', 'taker') OR liquidity IS NULL",
            name="ck_trades_liquidity_valid",
        ),
    )
    op.create_index("ix_trades_market_id", "trades", ["market_id"])
    op.create_index("ix_trades_venue", "trades", ["venue"])
    op.create_index("ix_trades_mode", "trades", ["mode"])
    op.create_index("ix_trades_executed_at", "trades", ["executed_at"])
    op.create_index("ix_trades_maker_address", "trades", ["maker_address"])
    op.create_index("ix_trades_taker_address", "trades", ["taker_address"])
    op.create_index("ix_trades_trade_id", "trades", ["trade_id"], unique=True)

    # --- positions -----------------------------------------------------
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("venue", sa.String(16), nullable=False),
        sa.Column("mode", sa.String(8), nullable=False),
        sa.Column("intent_id", sa.String(64), nullable=True),
        sa.Column("token_id", sa.String(100), nullable=False),
        sa.Column("outcome", sa.String(50), nullable=False),
        sa.Column("size", sa.Float(), nullable=False),
        sa.Column("avg_entry_price", sa.Float(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("current_price", sa.Float(), nullable=False),
        sa.Column("current_value", sa.Float(), nullable=False),
        sa.Column("unrealized_pnl", sa.Float(), nullable=False),
        sa.Column("unrealized_pnl_pct", sa.Float(), nullable=False),
        sa.Column("realized_pnl", sa.Float(), nullable=False),
        sa.Column("hold_to_resolution", sa.Boolean(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settlement_outcome", sa.String(50), nullable=True),
        sa.Column("extra_data", _JSON_TYPE, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"]),
        sa.CheckConstraint(
            "venue IN ('polymarket', 'kalshi')", name="ck_positions_venue_valid"
        ),
        sa.CheckConstraint(
            "mode IN ('paper', 'live')", name="ck_positions_mode_valid"
        ),
    )
    op.create_index("ix_positions_market_id", "positions", ["market_id"])
    op.create_index("ix_positions_venue", "positions", ["venue"])
    op.create_index("ix_positions_mode", "positions", ["mode"])
    op.create_index("ix_positions_intent_id", "positions", ["intent_id"])
    op.create_index("ix_positions_token_id", "positions", ["token_id"])
    op.create_index("ix_positions_opened_at", "positions", ["opened_at"])

    # --- backtests -----------------------------------------------------
    op.create_table(
        "backtests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(200), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("initial_capital", sa.Float(), nullable=False),
        sa.Column("parameters", _JSON_TYPE, nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="backteststatus",
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("final_capital", sa.Float(), nullable=True),
        sa.Column("total_return", sa.Float(), nullable=True),
        sa.Column("total_return_pct", sa.Float(), nullable=True),
        sa.Column("annualized_return", sa.Float(), nullable=True),
        sa.Column("sharpe_ratio", sa.Float(), nullable=True),
        sa.Column("sortino_ratio", sa.Float(), nullable=True),
        sa.Column("max_drawdown", sa.Float(), nullable=True),
        sa.Column("max_drawdown_pct", sa.Float(), nullable=True),
        sa.Column("volatility", sa.Float(), nullable=True),
        sa.Column("total_trades", sa.Integer(), nullable=False),
        sa.Column("winning_trades", sa.Integer(), nullable=False),
        sa.Column("losing_trades", sa.Integer(), nullable=False),
        sa.Column("win_rate", sa.Float(), nullable=True),
        sa.Column("avg_win", sa.Float(), nullable=True),
        sa.Column("avg_loss", sa.Float(), nullable=True),
        sa.Column("profit_factor", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("equity_curve", _JSON_TYPE, nullable=False),
        sa.Column("extra_data", _JSON_TYPE, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"]),
    )
    op.create_index("ix_backtests_strategy_id", "backtests", ["strategy_id"])
    op.create_index("ix_backtests_status", "backtests", ["status"])
    op.create_index("ix_backtests_created_at", "backtests", ["created_at"])

    # --- backtest_trades -------------------------------------------------
    op.create_table(
        "backtest_trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("backtest_id", sa.Integer(), nullable=False),
        sa.Column("market_condition_id", sa.String(66), nullable=False),
        sa.Column("token_id", sa.String(100), nullable=False),
        sa.Column("side", _ORDER_SIDE_ENUM, nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("exit_price", sa.Float(), nullable=True),
        sa.Column("size", sa.Float(), nullable=False),
        sa.Column("fee", sa.Float(), nullable=False),
        sa.Column("entry_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exit_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pnl", sa.Float(), nullable=True),
        sa.Column("pnl_pct", sa.Float(), nullable=True),
        sa.Column("signal_name", sa.String(100), nullable=True),
        sa.Column("signal_strength", sa.Float(), nullable=True),
        sa.Column("extra_data", _JSON_TYPE, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["backtest_id"], ["backtests.id"]),
    )
    op.create_index(
        "ix_backtest_trades_backtest_id", "backtest_trades", ["backtest_id"]
    )
    op.create_index(
        "ix_backtest_trades_entry_time", "backtest_trades", ["entry_time"]
    )

    # --- intents -------------------------------------------------------
    op.create_table(
        "intents",
        sa.Column("id", sa.String(64), nullable=False),
        sa.Column("kind", sa.String(16), nullable=False),
        sa.Column("strategy", sa.String(100), nullable=False),
        sa.Column("mode", sa.String(8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(16),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("legs", _JSON_TYPE, nullable=False),
        sa.Column("score", _JSON_TYPE, nullable=False),
        sa.Column("extra_data", _JSON_TYPE, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "kind IN ('single', 'complement', 'bundle', 'cross_venue')",
            name="ck_intents_kind_valid",
        ),
        sa.CheckConstraint("mode IN ('paper', 'live')", name="ck_intents_mode_valid"),
        sa.CheckConstraint(
            "status IN ('pending', 'executed', 'rejected', 'expired')",
            name="ck_intents_status_valid",
        ),
    )
    op.create_index("ix_intents_created_at", "intents", ["created_at"])
    op.create_index("ix_intents_mode", "intents", ["mode"])
    op.create_index("ix_intents_status", "intents", ["status"])


def downgrade() -> None:
    # --- intents ---
    op.drop_index("ix_intents_status", table_name="intents")
    op.drop_index("ix_intents_mode", table_name="intents")
    op.drop_index("ix_intents_created_at", table_name="intents")
    op.drop_table("intents")

    # --- backtest_trades ---
    op.drop_index("ix_backtest_trades_entry_time", table_name="backtest_trades")
    op.drop_index("ix_backtest_trades_backtest_id", table_name="backtest_trades")
    op.drop_table("backtest_trades")

    # --- backtests ---
    op.drop_index("ix_backtests_created_at", table_name="backtests")
    op.drop_index("ix_backtests_status", table_name="backtests")
    op.drop_index("ix_backtests_strategy_id", table_name="backtests")
    op.drop_table("backtests")
    op.execute("DROP TYPE IF EXISTS backteststatus")

    # --- positions ---
    op.drop_index("ix_positions_opened_at", table_name="positions")
    op.drop_index("ix_positions_token_id", table_name="positions")
    op.drop_index("ix_positions_intent_id", table_name="positions")
    op.drop_index("ix_positions_mode", table_name="positions")
    op.drop_index("ix_positions_venue", table_name="positions")
    op.drop_index("ix_positions_market_id", table_name="positions")
    op.drop_table("positions")

    # --- trades ---
    op.drop_index("ix_trades_trade_id", table_name="trades")
    op.drop_index("ix_trades_taker_address", table_name="trades")
    op.drop_index("ix_trades_maker_address", table_name="trades")
    op.drop_index("ix_trades_executed_at", table_name="trades")
    op.drop_index("ix_trades_mode", table_name="trades")
    op.drop_index("ix_trades_venue", table_name="trades")
    op.drop_index("ix_trades_market_id", table_name="trades")
    op.drop_table("trades")

    # --- orders ---
    op.drop_index("ix_orders_order_id", table_name="orders")
    op.drop_index("ix_orders_created_at", table_name="orders")
    op.drop_index("ix_orders_status", table_name="orders")
    op.drop_index("ix_orders_mode", table_name="orders")
    op.drop_index("ix_orders_intent_id", table_name="orders")
    op.drop_index("ix_orders_venue", table_name="orders")
    op.drop_index("ix_orders_market_id", table_name="orders")
    op.drop_table("orders")
    op.execute("DROP TYPE IF EXISTS orderstatus")
    op.execute("DROP TYPE IF EXISTS ordertype")

    # `orderside` is shared by orders/trades/backtest_trades, all dropped
    # by this point — safe to drop the type now.
    op.execute("DROP TYPE IF EXISTS orderside")

    # --- strategies ---
    op.drop_table("strategies")
    op.execute("DROP TYPE IF EXISTS strategytype")

    # --- market_prices ---
    op.drop_index("ix_market_prices_market_timestamp", table_name="market_prices")
    op.drop_index("ix_market_prices_timestamp", table_name="market_prices")
    op.drop_index("ix_market_prices_market_id", table_name="market_prices")
    op.drop_table("market_prices")

    # --- markets ---
    op.drop_index("ix_markets_condition_id", table_name="markets")
    op.drop_index("ix_markets_end_date", table_name="markets")
    op.drop_index("ix_markets_venue", table_name="markets")
    op.drop_index("ix_markets_is_active", table_name="markets")
    op.drop_index("ix_markets_category", table_name="markets")
    op.drop_table("markets")
