"""Cross-venue event equivalence table: event_links.

Revision ID: 005
Revises: 004
Create Date: 2026-09-04 00:04:00.000000+00:00

Creates the single table behind PLAN.md D9 (`app.models.event_link.
EventLink`, T17): one row per claim that a Polymarket market and a Kalshi
market pay out on the same underlying fact, carrying the deterministic
matcher's confidence, the evidence components behind it, and — the point
of the whole subsystem — a review lifecycle only a human advances.

Hand-written from the model rather than autogenerated, and checked
against `str(CreateTable(Base.metadata.tables["event_links"]).compile(
dialect=postgresql.dialect()))` column for column and constraint for
constraint before being written down, for the reason `004`'s docstring
gives: if this chain and a fresh `create_all()` diverge, they diverge
forever.

Offline-safe (GUARDRAILS.md §4): no `CREATE TYPE`, no server-side
reflection, nothing that needs a live connection — `alembic upgrade head
--sql` renders it whole. `status` is a `VARCHAR` + `CHECK` rather than a
Postgres enum on purpose: `004` had to hand-manage `orderside`'s
`CREATE TYPE` to keep three tables from colliding on it, and a
single-table lifecycle column is not worth inheriting that problem.

`server_default='proposed'` is deliberate and load-bearing, not
convenience. A row inserted without an explicit lifecycle value lands in
the review queue, which is the safe default: the failure mode this whole
subsystem exists to prevent is a machine-generated equivalence reaching
the router without a person having read both rules texts (PLAN.md R1).
The `CHECK` constraint is defence in depth behind the API routes that own
the transitions.

`id` is `SERIAL`: link ids live in their OWN namespace and are never
folded into an order identity. `app.models.intent`'s docstring records
that `client_order_id`/`trade_id` are globally unique across paper AND
live, so a link id that leaked into an order id could let a paper row
block a live one.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "005"
down_revision: Union[str, None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: Mirrors `app.models.base.JSONDict`: plain JSON on SQLite (tests),
#: JSONB on Postgres. Declared here rather than imported so this
#: migration stays valid if the model module is later refactored — a
#: migration describes the schema as it was, not as the models are now
#: (same rationale `003`/`004` used).
_JSON_TYPE = sa.JSON(none_as_null=True).with_variant(
    postgresql.JSONB(none_as_null=True), "postgresql"
)


def upgrade() -> None:
    op.create_table(
        "event_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("venue_a", sa.String(16), nullable=False),
        sa.Column("market_a", sa.String(128), nullable=False),
        sa.Column("venue_b", sa.String(16), nullable=False),
        sa.Column("market_b", sa.String(128), nullable=False),
        sa.Column("outcome_map", _JSON_TYPE, nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", _JSON_TYPE, nullable=False),
        sa.Column(
            "status",
            sa.String(16),
            server_default="proposed",
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(100), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "venue_a",
            "market_a",
            "venue_b",
            "market_b",
            name="uq_event_links_pair",
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'approved', 'rejected')",
            name="ck_event_links_status_valid",
        ),
        sa.CheckConstraint(
            "venue_a IN ('polymarket', 'kalshi')",
            name="ck_event_links_venue_a_valid",
        ),
        sa.CheckConstraint(
            "venue_b IN ('polymarket', 'kalshi')",
            name="ck_event_links_venue_b_valid",
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0",
            name="ck_event_links_confidence_range",
        ),
    )
    op.create_index("ix_event_links_status", "event_links", ["status"])
    op.create_index(
        "ix_event_links_venue_a_market_a", "event_links", ["venue_a", "market_a"]
    )
    op.create_index(
        "ix_event_links_venue_b_market_b", "event_links", ["venue_b", "market_b"]
    )


def downgrade() -> None:
    op.drop_index("ix_event_links_venue_b_market_b", table_name="event_links")
    op.drop_index("ix_event_links_venue_a_market_a", table_name="event_links")
    op.drop_index("ix_event_links_status", table_name="event_links")
    op.drop_table("event_links")
