"""Recorded order-book depth table: book_snapshots.

Revision ID: 006
Revises: 005
Create Date: 2026-09-04 00:05:00.000000+00:00

Creates the single table behind PLAN.md D6/D10 (`app.models.book_snapshot.
BookSnapshot`, T21): one row per observed order book for one
`(venue, market_id, outcome)` at one instant, so
`app.services.backtesting.data_replay.DataReplayer` can attach REAL depth
to a replayed snapshot instead of always falling back to
`app.execution.fill_engine.synthesize_book`'s fabricated one-level book
(GUARDRAILS.md §1.7).

Hand-written from the model rather than autogenerated, and checked
against `str(CreateTable(Base.metadata.tables["book_snapshots"]).compile(
dialect=postgresql.dialect()))` column for column and constraint for
constraint before being written down, for the reason `004`/`005`'s
docstrings give: if this chain and a fresh `create_all()` diverge, they
diverge forever.

Offline-safe (GUARDRAILS.md §4): no `CREATE TYPE`, no server-side
reflection, nothing that needs a live connection — `alembic upgrade head
--sql` renders it whole. Like `price_history` (migration `001`), this is
a time-series table keyed by `ts`, so it gets the SAME TimescaleDB
hypertable guard `001` uses: a `DO $$ ... $$` block that only calls
`create_hypertable` when the `timescaledb` extension is actually
installed, so the offline SQL render and a plain Postgres install (no
TimescaleDB) both succeed with no error.

`id` is `SERIAL` and plays no role in any other table's identity — unlike
`005`'s note about link ids never leaking into an order id, there is no
comparable risk here since nothing downstream ever references a
`book_snapshots.id`; every consumer (`DataReplayer`,
`DataCollector.collect_books`'s own idempotency check) looks a row up by
the natural key `(venue, market_id, outcome, ts)`.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "006"
down_revision: Union[str, None] = "005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: Mirrors `app.models.base.JSONList`: plain JSON on SQLite (tests),
#: JSONB on Postgres. Declared here rather than imported so this
#: migration stays valid if the model module is later refactored — a
#: migration describes the schema as it was, not as the models are now
#: (same rationale `003`/`004`/`005` used).
_JSON_TYPE = sa.JSON(none_as_null=True).with_variant(
    postgresql.JSONB(none_as_null=True), "postgresql"
)


def upgrade() -> None:
    op.create_table(
        "book_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("venue", sa.String(16), nullable=False),
        sa.Column("market_id", sa.String(128), nullable=False),
        sa.Column("outcome", sa.String(50), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bids", _JSON_TYPE, nullable=False),
        sa.Column("asks", _JSON_TYPE, nullable=False),
        sa.Column("tick_size", sa.Float(), nullable=False),
        sa.Column("min_size", sa.Float(), nullable=False),
        sa.Column(
            "depth_source",
            sa.String(16),
            server_default="recorded",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "venue",
            "market_id",
            "outcome",
            "ts",
            name="uq_book_snapshots_venue_market_outcome_ts",
        ),
        sa.CheckConstraint(
            "venue IN ('polymarket', 'kalshi')",
            name="ck_book_snapshots_venue_valid",
        ),
        sa.CheckConstraint(
            "depth_source IN ('recorded', 'synthetic')",
            name="ck_book_snapshots_depth_source_valid",
        ),
        sa.CheckConstraint(
            "tick_size > 0.0 AND tick_size <= 1.0",
            name="ck_book_snapshots_tick_size_range",
        ),
        sa.CheckConstraint(
            "min_size >= 0.0",
            name="ck_book_snapshots_min_size_nonnegative",
        ),
    )
    op.create_index("ix_book_snapshots_ts", "book_snapshots", ["ts"])
    op.create_index(
        "ix_book_snapshots_venue_market_outcome",
        "book_snapshots",
        ["venue", "market_id", "outcome"],
    )

    # Convert book_snapshots to a TimescaleDB hypertable, exactly like
    # `001` does for `price_history` — guarded so this succeeds whether
    # or not the `timescaledb` extension is installed (including the
    # `alembic upgrade head --sql` offline render, which has no
    # extension catalog to query at all).
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'timescaledb') THEN
                -- TimescaleDB refuses to convert a table carrying ANY unique
                -- index that omits the partitioning column, and `book_snapshots_pkey`
                -- is on `id` alone. Without this DROP the conversion fails with
                -- "cannot create a unique index without the column ts" and
                -- takes the whole migration chain down with it -- verified
                -- against timescale/timescaledb:latest-pg15.
                --
                -- Dropping it is safe rather than a concession: row uniqueness
                -- is already enforced by the natural key
                -- `uq_book_snapshots_venue_market_outcome_ts (venue, market_id, outcome, ts)`,
                -- created above, which DOES contain the partitioning column. The
                -- surrogate PK adds nothing here, `id` keeps its sequence and
                -- stays unique, and no foreign key references this table.
                ALTER TABLE book_snapshots DROP CONSTRAINT IF EXISTS book_snapshots_pkey;
                PERFORM create_hypertable('book_snapshots', 'ts', if_not_exists => TRUE);
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    op.drop_index("ix_book_snapshots_venue_market_outcome", table_name="book_snapshots")
    op.drop_index("ix_book_snapshots_ts", table_name="book_snapshots")
    op.drop_table("book_snapshots")
